### ISSUE TITLE
Cannot scroll odds with mouse on desktop 

### ISSUE THREAD

**Issue by adrianpawlik** [cephiednomiko/odds-table#5]
Mouse scroll seems disabled for desktop users.

**Comment by cephiednomiko** [comment]
I implemented wheel event listener so that user can use mouse wheel to scroll the whole container as with using arrows. If by this issue You meant to retain normal scrollbar, I disabled it on purpose because default browser scrollbar usually doesn't look good (it would not go well with the graphic project). I could've added custom scrollbar, but the graphic project didn't include how it should look.
